### ISSUE TITLE
Timestamps for upload might be slightly off

### ISSUE THREAD

**Issue by Steeven9** [Carrisiland/vimtok#7]

**Comment by thefooly** [comment]
In all the mongoose schemas you wrote:
```javascript
default: Date.now().toString();
```
Check this again.

Edit: 
check also
```javascript
default: [];
```

**Comment by Steeven9** [comment]
Oh, I had that too in a mastery check lol. Remove the parenthesis from `Date.now` and it should work

**Comment by thefooly** [comment]
Yes, but be careful that by just removing the parentheses you will get a syntax error. The correct way to do it is to pass the following callback function:
```javascript
default: () => {return Date.now().toString()}
```
or
```javascript
default: () => Date.now().toString()
```

Mongoose will call the callback function when the document is created. If you write ```Date.now().toString()``` the function is evaluated when the schema is created, thus you get the same value for all the documents.

Similarly you should write for arrays and objects
```javascript
default () => []
```
```javascript
default () => {}
```
